### ISSUE TITLE
The dataset link failed

### ISSUE THREAD

**Issue by yixiaoshenghua** [xfgao/VRKitchen#13]
Dear author, I'm very interested in your work. I read and tried to run this environment but found that the data provided in the link(https://drive.google.com/file/d/1QTAvO6Uwm_paGAfGMveKHCMxwAxGAyi_/view?usp=sharing) is invalid. Can you provide a valid link? Thank you very much!
![image](https://github.com/user-attachments/assets/d01aaacc-c7c2-44c5-9454-3d573253d03b)

**Comment by xfgao** [comment]
Thanks for the interest. 
Here is the new link: https://drive.google.com/file/d/1yahh4RGl7ofepoJin57n2mV1g-i7-T0L/view?usp=sharing

**Comment by yixiaoshenghua** [comment]
Thank you very much!
